
CC = g++
SRC = main.cpp characters.cpp combat.cpp utility.cpp
HEADER = characters.h combat.h utility.h

all: assignment4

assignment4:
	$(CC) -std=c++0x ${SRC} ${HEADER} -o assignment4

clean:
	rm -rf *.o assignment4