CC = g++
SRC = main.cpp utility.cpp game.cpp player.cpp ship.cpp map.cpp combat.cpp npc.cpp
HEADER = utility.h game.h player.h ship.h map.h combat.h npc.h

all: pirateRescue

pirateRescue:
	$(CC) -std=c++0x ${SRC} ${HEADER} -o pirateRescue
clean:
	rm -rf *.o pirateRescue